services:
  mail:
    image: cellules/mail:latest
    container_name: mail-app
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:password@mail-db:5432/maildb
      CORE_WS_URL: ws://core-app:3000

      SMTP_HOST: smtp.example.com
      SMTP_PORT: 465
      SMTP_TLS: true
      SMTP_USER: mail@example.com
      SMTP_PASS: password

      IMAP_HOST: imap.example.com
      IMAP_PORT: 993
      IMAP_TLS: true
      IMAP_USER: mail@example.com
      IMAP_PASS: password
    networks:
      - cellule

  db:
    image: postgres:13
    container_name: mail-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maildb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cellule
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  cellule:
    external: true
